export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { fullName, witness1, witness2, templateType } = req.body;

    if (!fullName || !witness1 || !witness2) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Generate document text dynamically
    const document = `
    COMMON CARRY DECLARATION

    I, ${fullName}, declare this as my lawful notice under common law.

    Witness 1: ${witness1}
    Witness 2: ${witness2}

    Signed on ${new Date().toLocaleDateString()}.

    -- Generated by TSSA Document Automation Portal
    `;

    res.setHeader('Content-Type', 'text/plain');
    res.status(200).send(document);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Server error' });
  }
}
